name: Déploiemehnt application
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Environnement de déploiement'    
        required: true
        default: 'dev'

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
    - name: Démarrage Workflow
      run: echo "Démarrage du Workflow"
